name: titanic-env
dependencies:
  - python=3.9
  - pip
  - pip:
    - pip
    - setuptools
    - wheel
    - pandas
    - scikit-learn
    - nltk
    - matplotlib
    - numpy
    - seaborn
    - ipykernel
    - jinja2
